package tripismapiutilities

//
// Generated by ChatGPT - https://chat.openai.com/ - on 2026-04-28
//

import (
	"sort"
	"strings"
)

// MatchHotelNames compares two hotel names and returns whether they likely refer to the same hotel along with a confidence score (0-100)
// The algorithm includes:
// 1. Normalization: lowercasing, removing accents, punctuation, and common stop words.
// 2. Exact match check on normalized tokens.
// 3. Subset match check (one name's tokens are a subset of the other's).
// 4. Fuzzy token overlap (allowing for minor typos).
// 5. Penalizing mismatches in brand or location indicators.
func MatchHotelNames(a, b string) (bool, int) {
	tokensA := normalize(a)
	tokensB := normalize(b)

	score := 0

	// Exact match
	if equalSlices(tokensA, tokensB) {
		return true, 100
	}

	// Subset match
	if isSubset(tokensA, tokensB) || isSubset(tokensB, tokensA) {
		score += 80
	}

	// Fuzzy token match
	common := fuzzyTokenOverlap(tokensA, tokensB)
	if common > 0 {
		score += common * 10
	}

	// Penalize brand mismatch
	if brandMismatch(tokensA, tokensB) {
		score -= 100
	}

	// Penalize location mismatch
	if locationMismatch(tokensA, tokensB) {
		score -= 100
	}

	return score >= 75, score
}

// --- Normalization ---
func normalize(s string) []string {
	s = strings.ToLower(s)
	s = RemoveAccents(s)
	s = RemovePunctuation(s)

	replacements := map[string]string{
		"hotel":      "",
		"the":        "",
		"and":        "",
		"&":          "",
		"by":         "",
		"collection": "",
		"a":          "",
		"an":         "",
		"of":         "",
		"ihg":        "",
		"lvx":        "",
	}

	for k, v := range replacements {
		s = strings.ReplaceAll(s, k, v)
	}

	tokens := strings.Fields(s)
	sort.Strings(tokens)

	return tokens
}

// --- Helpers ---
func equalSlices(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func isSubset(a, b []string) bool {
	set := make(map[string]bool)
	for _, t := range b {
		set[t] = true
	}
	for _, t := range a {
		if !set[t] {
			return false
		}
	}
	return true
}

// --- Fuzzy matching ---
func fuzzyTokenOverlap(a, b []string) int {
	count := 0
	for _, ta := range a {
		for _, tb := range b {
			if levenshtein(ta, tb) <= 1 {
				count++
				break
			}
		}
	}
	return count
}

// Simple Levenshtein (optimized enough for short tokens)
func levenshtein(a, b string) int {
	if a == b {
		return 0
	}
	if len(a) == 0 {
		return len(b)
	}
	if len(b) == 0 {
		return len(a)
	}

	dp := make([][]int, len(a)+1)
	for i := range dp {
		dp[i] = make([]int, len(b)+1)
	}

	for i := 0; i <= len(a); i++ {
		dp[i][0] = i
	}
	for j := 0; j <= len(b); j++ {
		dp[0][j] = j
	}

	for i := 1; i <= len(a); i++ {
		for j := 1; j <= len(b); j++ {
			cost := 0
			if a[i-1] != b[j-1] {
				cost = 1
			}

			dp[i][j] = min(
				dp[i-1][j]+1,
				dp[i][j-1]+1,
				dp[i-1][j-1]+cost,
			)
		}
	}

	return dp[len(a)][len(b)]
}

func min(a, b, c int) int {
	if a < b && a < c {
		return a
	}
	if b < c {
		return b
	}
	return c
}

// --- Brand mismatch ---
var brands = []string{
	"hyatt", "hilton", "marriott", "radisson",
	"intercontinental", "four", "ritz", "shangrila",
}

func brandMismatch(a, b []string) bool {
	ba := extractBrand(a)
	bb := extractBrand(b)
	return ba != "" && bb != "" && ba != bb
}

func extractBrand(tokens []string) string {
	for _, t := range tokens {
		for _, b := range brands {
			if t == b {
				return b
			}
		}
	}
	return ""
}

// --- Location mismatch (basic heuristic) ---
func locationMismatch(a, b []string) bool {
	locA := lastToken(a)
	locB := lastToken(b)

	if locA != "" && locB != "" && locA != locB {
		return true
	}
	return false
}

func lastToken(tokens []string) string {
	if len(tokens) == 0 {
		return ""
	}
	return tokens[len(tokens)-1]
}
